# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInfo',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('actionName', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='r_action',
            field=models.ManyToManyField(to='CRM.ActionInfo'),
        ),
    ]
